before:
  hooks:
    - go mod tidy
builds:
  - id: tke-auth-controller
    binary: tke-auth-controller
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "harbor.pubg.io/public/tke-auth-controller:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "harbor.pubg.io/public/tke-auth-controller:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: "harbor.pubg.io/public/tke-auth-controller:{{ .Version }}"
    image_templates:
      - "harbor.pubg.io/public/tke-auth-controller:{{ .Version }}-amd64"
      - "harbor.pubg.io/public/tke-auth-controller:{{ .Version }}-arm64"
release:
  disable: true
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
# See https://blog.devgenius.io/goreleaser-build-multi-arch-docker-images-8dd9a7903675
