apiVersion: v1
kind: ServiceAccount
metadata:
  name: tke-auth-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tke-auth-controller-role
  namespace: default
rules:
  - verbs:
      - get
      - update
      - delete
      - create
    apiGroups:
      - rbac.authorization.k8s.io
      - ""
    resources:
      - configmaps
      - clusterrolebindings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tke-auth-controller-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tke-auth-controller-role
subjects:
  - kind: ServiceAccount
    name: tke-auth-controller-sa
    namespace: default
