apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-sample
  annotations:
    tke-auth/binding: "true"
data:
  bindingName: "xtrm-platform-team-default"
  roleName: "xtrm:user:full-control"
  users: |
    defaultUserValueType: subAccountId
    users:
      - valueType: subAccountId
        value: "200020745365"
