name: "build tke-auth-controller"
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_image:
    name: build docker image using Dockerfile
    runs-on: ["self-hosted", "Linux", "DevOps"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # to fetch all tags
      - name: setup node 16.x # setup-node@v2 can't used on enterprise github.
        shell: bash
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: setup libraries
        shell: bash
        run: |
          sudo npm i -g yarn
          sudo yarn global add semver
      - name: get semver
        id: semver
        shell: bash
        run: |
          current_tag=$(git describe --tags --abbrev=0)
          echo "current_tag: $current_tag"
          semver=$(semver "$current_tag")
          echo "extracted semver: $semver"
          echo "::set-output name=SEMVER::$semver"
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build . --tag "zzzz465/0e43d9d1140c48102ef:${{ steps.semver.outputs.SEMVER }}"
          docker push zzzz465/0e43d9d1140c48102ef:${{ steps.semver.outputs.SEMVER }}
      - name: slack-notify
        uses: 8398a7/action-slack@v3.9.1
        with:
          github_base_url: https://github.krafton.com
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `commit: ${ process.env.AS_REPO }@${ process.env.AS_COMMIT }\nauthor: ${ process.env.AS_AUTHOR }\nmessage: ${ process.env.AS_MESSAGE }\naction: ${ process.env.AS_ACTION }`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PLATFORM_SLACK_WEBHOOK_URL }}
        if: always()
